export const loremIpsum = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa enim nec dui nunc mattis enim ut. Risus nullam eget felis eget. Sagittis eu volutpat odio facilisis. Nulla aliquet enim tortor at. Bibendum ut tristique et egestas quis ipsum suspendisse. Sollicitudin aliquam ultrices sagittis orci a. In hac habitasse platea dictumst quisque sagittis purus sit. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl vel. Lectus magna fringilla urna porttitor rhoncus dolor purus non enim. Quisque egestas diam in arcu cursus euismod quis viverra nibh. Morbi quis commodo odio aenean sed adipiscing diam donec. Nunc id cursus metus aliquam eleifend mi in. Et netus et malesuada fames ac turpis egestas integer eget. Libero justo laoreet sit amet. Egestas pretium aenean pharetra magna ac. Habitasse platea dictumst quisque sagittis purus.

Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. Amet est placerat in egestas erat imperdiet sed euismod. Sed blandit libero volutpat sed cras ornare. Facilisi cras fermentum odio eu feugiat pretium nibh. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Facilisis gravida neque convallis a cras. Quam viverra orci sagittis eu volutpat. Nibh praesent tristique magna sit amet purus gravida quis. Nibh cras pulvinar mattis nunc sed blandit. Quis auctor elit sed vulputate mi sit amet. Faucibus purus in massa tempor nec feugiat. Vitae et leo duis ut diam quam. Pretium fusce id velit ut tortor pretium viverra suspendisse. Donec pretium vulputate sapien nec sagittis. Viverra aliquet eget sit amet.

Eget duis at tellus at urna. Sem et tortor consequat id porta nibh venenatis cras sed. Nunc sed augue lacus viverra vitae congue eu consequat ac. Cursus risus at ultrices mi tempus imperdiet nulla malesuada. Tristique sollicitudin nibh sit amet commodo nulla facilisi. Ac odio tempor orci dapibus ultrices in iaculis nunc. Nam at lectus urna duis convallis. Ultrices eros in cursus turpis massa. Ac odio tempor orci dapibus ultrices in iaculis. Nisl vel pretium lectus quam id leo in vitae turpis. Neque convallis a cras semper auctor neque vitae tempus. Viverra aliquet eget sit amet tellus cras. Turpis tincidunt id aliquet risus feugiat. Eu mi bibendum neque egestas congue.

At augue eget arcu dictum. Cursus eget nunc scelerisque viverra mauris in. Adipiscing tristique risus nec feugiat in fermentum posuere. Pellentesque eu tincidunt tortor aliquam nulla facilisi. Eu volutpat odio facilisis mauris sit. Mi sit amet mauris commodo quis imperdiet. Varius quam quisque id diam vel quam elementum pulvinar. Nunc mattis enim ut tellus elementum. Ultricies mi eget mauris pharetra. Turpis cursus in hac habitasse. Morbi tincidunt ornare massa eget egestas purus viverra accumsan. Lacus luctus accumsan tortor posuere ac ut consequat semper. Dignissim convallis aenean et tortor at. Id diam maecenas ultricies mi eget mauris.

Commodo nulla facilisi nullam vehicula ipsum. Diam quis enim lobortis scelerisque fermentum dui. Ridiculus mus mauris vitae ultricies leo integer. Est velit egestas dui id. Euismod nisi porta lorem mollis aliquam. Quis auctor elit sed vulputate mi sit amet. Interdum varius sit amet mattis vulputate enim nulla aliquet. Fames ac turpis egestas maecenas pharetra. Sociis natoque penatibus et magnis dis parturient. Nunc eget lorem dolor sed viverra ipsum nunc.`;
